import clsx from 'clsx';
import localFont from 'next/font/local';
import { Inter } from 'next/font/google';

import './globals.css';

const geistSans = localFont({
  src: '../fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});

const geistMono = localFont({
  src: '../fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap', // Matches `display=swap` in your link
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={clsx(inter.variable, geistSans.variable, geistMono.variable, 'antialiased bg-white')}>
        <div className="flex flex-col max-w-[506px] m-auto h-screen w-full overflow-hidden">{children}</div>
      </body>
    </html>
  );
}
