import type { Metadata } from 'next';

import PageTransition from '@/components/PageTransition';
import { heading } from '@/lib/fonts';
import BaseProvider from '@/providers/base';
import '@/styles/globals.css';

import { cn } from '@kit/ui/utils';

export const metadata: Metadata = {
  title: 'BondX',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script src="//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js"></script>
      </head>
      <body className={cn('bg-white antialiased', heading.variable)}>
        <BaseProvider>
          <div className="mobile-view" id="root-parent">
            <div className="mobile-wrapper">
              <PageTransition
                duration={500}
                className="mobile-content"
                transitionClasses={{
                  enter: 'opacity-100',
                  exit: 'opacity-0',
                }}
              >
                {children}
              </PageTransition>
            </div>
          </div>
        </BaseProvider>
      </body>
    </html>
  );
}
