import type { Metadata } from 'next';

import Viewport from '@/components/Viewport';
import { heading } from '@/lib/fonts';
import '@/styles/globals.css';

import { cn } from '@kit/ui/utils';

export const metadata: Metadata = {
  title: 'BondX',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn('bg-white antialiased', heading.variable)}>
        <Viewport />
        <div className="mobile-view" id="root-parent">
          <div className="mobile-wrapper">
            <div className="mobile-content">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
