import type { Metadata } from 'next';

import PageTransition from '@/components/PageTransition';

export const metadata: Metadata = {
  title: 'BondX',
  description: 'Generated by create next app',
};

export default function UserLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="mobile-view" id="root-parent">
      <div className="mobile-wrapper">
        <PageTransition
          duration={500}
          className="mobile-content"
          transitionClasses={{
            enter: 'opacity-100',
            exit: 'opacity-0',
          }}
        >
          {children}
        </PageTransition>
      </div>
    </div>
  );
}
